export const CHANGE_USERNAME_START = 'CHANGE_USERNAME_START';
export const CHANGE_USERNAME_SUCCESS = 'CHANGE_USERNAME_SUCCESS';
export const CHANGE_USERNAME_FAIL = 'CHANGE_USERNAME_FAIL';


export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';


export const SAVE_PROFILE_START = 'SAVE_PROFILE_START';
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_FAIL = 'SAVE_PROFILE_FAIL';


export const PASSWORD_RESET_CONFIRM_START = 'PASSWORD_RESET_CONFIRM_START';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';


export const USER_ACTIVATE_START = 'USER_ACTIVATE_START';
export const USER_ACTIVATE_SUCCESS = 'USER_ACTIVATE_SUCCESS';
export const USER_ACTIVATE_FAIL = 'USER_ACTIVATE_FAIL';


export const SEND_USER_ACTIVATION_MAIL_START = 'SEND_USER_ACTIVATION_MAIL_START';
export const SEND_USER_ACTIVATION_MAIL_SUCCESS = 'SEND_USER_ACTIVATION_MAIL_SUCCESS';
export const SEND_USER_ACTIVATION_MAIL_FAIL = 'SEND_USER_ACTIVATION_MAIL_FAIL';


export const SET_USER_EMAIL_START = 'SET_USER_EMAIL_START';
export const SET_USER_EMAIL_SUCCESS = 'SET_USER_EMAIL_SUCCESS';
export const SET_USER_EMAIL_FAIL = 'SET_USER_EMAIL_FAIL';