export const LOAD_ANOTHER_USERS_START = 'LOAD_ANOTHER_USERS_START';
export const LOAD_ANOTHER_USERS_SUCCESS = 'LOAD_ANOTHER_USERS_SUCCESS';
export const LOAD_ANOTHER_USERS_FAIL = 'LOAD_ANOTHER_USERS_FAIL';
