export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';


export const GET_USER_INFO_START = 'GET_USER_INFO_START';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';


export const LOGOUT_USER_START = 'LOGOUT_USER_START';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';

export const USER_FORM_LOGIN = 'USER_FORM_LOGIN';
export const USER_FORM_REGISTRATION = 'USER_FORM_REGISTRATION';


export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';


export const USER_VK_LOGIN_START = 'USER_VK_LOGIN_START';
export const USER_VK_LOGIN_SUCCESS = 'USER_VK_LOGIN_SUCCESS';
export const USER_VK_LOGIN_FAIL = 'USER_VK_LOGIN_FAIL';


export const USER_SOCIAL_LOGIN_START = 'USER_SOCIAL_LOGIN_START';
export const USER_SOCIAL_LOGIN_SUCCESS = 'USER_SOCIAL_LOGIN_SUCCESS';
export const USER_SOCIAL_LOGIN_FAIL = 'USER_SOCIAL_LOGIN_FAIL';

export const USER_GOOGLE_LOGIN_START = 'USER_GOOGLE_LOGIN_START';
export const USER_GOOGLE_LOGIN_SUCCESS = 'USER_GOOGLE_LOGIN_SUCCESS';
export const USER_GOOGLE_LOGIN_FAIL = 'USER_GOOGLE_LOGIN_FAIL';


export const USER_FACEBOOK_LOGIN_START = 'USER_FACEBOOK_LOGIN_START';
export const USER_FACEBOOK_LOGIN_SUCCESS = 'USER_FACEBOOK_LOGIN_SUCCESS';
export const USER_FACEBOOK_LOGIN_FAIL = 'USER_FACEBOOK_LOGIN_FAIL';
