export const LOAD_POSTS_START = 'LOAD_POSTS_START';
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_POSTS_FAIL = 'LOAD_POSTS_FAIL';


export const ADD_POST_START = 'ADD_POST_START';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAIL = 'ADD_POST_FAIL';


export const RATE_POST_START = 'RATE_POST_START';
export const RATE_POST_SUCCESS = 'RATE_POST_SUCCESS';
export const RATE_POST_FAIL = 'RATE_POST_FAIL';


export const UPDATE_POST_START = 'UPDATE_POST_START';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL';


export const RATE_POST_TYPE_LIKE = 1;
export const RATE_POST_TYPE_DISLIKE = 2;

export const CLEAN_POSTS = 'CLEAN_POSTS';


export const LOAD_POSTS_PERM_START = 'LOAD_POSTS_PERM_START';
export const LOAD_POSTS_PERM_SUCCESS = 'LOAD_POSTS_PERM_SUCCESS';
export const LOAD_POSTS_PERM_FAIL = 'LOAD_POSTS_PERM_FAIL';