export const LOAD_POSTS_START = 'LOAD_POSTS_START';
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_POSTS_FAIL = 'LOAD_POSTS_FAIL';


export const ADD_POST_START = 'ADD_POST_START';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAIL = 'ADD_POST_FAIL';


export const RATE_POST_START = 'RATE_POST_START';
export const RATE_POST_SUCCESS = 'RATE_POST_SUCCESS';
export const RATE_POST_FAIL = 'RATE_POST_FAIL';


export const LOAD_MORE_POSTS_START = 'LOAD_MORE_POSTS_START';
export const LOAD_MORE_POSTS_SUCCESS = 'LOAD_MORE_POSTS_SUCCESS';
export const LOAD_MORE_POSTS_FAIL = 'LOAD_MORE_POSTS_FAIL';

export const RATE_POST_TYPE_LIKE = 1;
export const RATE_POST_TYPE_DISLIKE = 2;


